name: Deploy Bot

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker stop vpn-bot || true
            docker rm vpn-bot || true
            cd ~/vpn_bot
            docker build -t vpn-bot .
            docker run -d               --name vpn-bot               --restart always               --env-file .env               vpn-bot
