script: |
  set -e
  echo "🚀 START DEPLOY"

  cd /tmp/vpn-bot || git clone https://github.com/NikitaKorovinskii/Bot-server.git /tmp/vpn-bot
  cd /tmp/vpn-bot
  git pull

  docker build -t vpn-bot .

  docker restart vpn-bot || docker run -d \
    --name vpn-bot \
    --restart always \
    --env-file /root/vpn_bot/.env \
    -v /var/run/docker.sock:/var/run/docker.sock \
    vpn-bot

  echo "✅ DONE"