name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            echo "🚀 START DEPLOY"

            rm -rf /tmp/vpn-bot

            git clone https://$GH_TOKEN@github.com/NikitaKorovinskii/Bot-server.git /tmp/vpn-bot

            cd /tmp/vpn-bot

            docker build --no-cache -t vpn-bot .

            docker rm -f vpn-bot || true

            docker run -d \
              --name vpn-bot \
              --restart always \
              --env-file /root/vpn_bot/.env \
              -v /var/run/docker.sock:/var/run/docker.sock \
              vpn-bot

            echo "✅ DONE"